/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.amazon;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    AmazonServer server = new AmazonServer();
    try {
      server.getWorldConnection();
    }
    catch (Exception e) {
      System.out.println(e);
    } 
  }
}
