# Generated by Django 4.0.1 on 2022-04-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(default='Purchasing', max_length=50),
        ),
    ]
