# Generated by Django 4.0.1 on 2022-04-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='truck_id',
            field=models.IntegerField(default=-1),
        ),
    ]
