# Generated by Django 4.0.1 on 2022-04-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_package_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='package',
            name='ups_account',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
