# Generated by Django 4.0.1 on 2022-04-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ups_verified',
            field=models.BooleanField(default=False),
        ),
    ]
