version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=amazon
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./frontend
      command: bash ./initserver.sh
      volumes:
        - ./frontend:/code
      depends_on:
        - db
  web:
      build: ./frontend
      user: nobody
      command: bash ./runserver.sh
      volumes:
        - ./frontend:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
  backend:
    build: ./backend
    command: bash -c "./gradlew run"
    ports:
      - "6666:6666"
      - "5678:5678" 
    depends_on:
      - web
volumes:
   data-volume: 